name: Build

on:
  workflow_run:
    workflows: [Update]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Check if today's tag exists
        id: tag
        run: |
          export PATH="/mingw64/bin:/C/Program Files/Git/bin:$PATH"

          today="$(date +%Y%m%d)"
          tag="$(cat tag.txt)"
          if [ "$tag" = "$today" ]; then
          	echo "skip=false" >> "$GITHUB_OUTPUT"
          	echo "tag=$today" >> "$GITHUB_OUTPUT"
          else
          	echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
        shell: 'C:/shells/msys2bash.cmd {0}'

      - name: Install dependencies
        if: ${{ steps.tag.outputs.skip == 'false' }}
        run: |
           pacman -S --noconfirm --needed --noprogressbar make mingw-w64-x86_64-gcc
        shell: 'C:/shells/msys2bash.cmd {0}'

      - name: Build tree-sitter modules
        if: ${{ steps.tag.outputs.skip == 'false' }}
        id: build
        run: |
          export PATH="/mingw64/bin:/C/Program Files/Git/bin:$PATH"

          mkdir -p dist/licenses

          git submodule foreach bash ../build.sh .
          cp language-manifest.txt dist/

          echo "summary<<EOF" >> "$GITHUB_OUTPUT"
          cat dist/language-manifest.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

          ls -l dist
        shell: 'C:/shells/msys2bash.cmd {0}'

      - name: Archive
        if: ${{ steps.tag.outputs.skip == 'false' }}
        id: archive
        run: |
          $ARCHIVE = "emacs-tree-sitter-module-${{ steps.tag.outputs.tag }}.zip"

          cd dist
          Compress-Archive -Path *.dll,language-manifest.txt,licenses -DestinationPath "../$ARCHIVE"
          cd ..
          $ARTIFACT_HASH = (Get-FileHash -Algorithm SHA256 "$ARCHIVE").Hash
          "$ARTIFACT_HASH  $ARCHIVE"| Out-File -Encoding ascii -File sha256sum.txt

          gc $env:GITHUB_OUTPUT

      - name: Create Release
        if: ${{ steps.tag.outputs.skip == 'false' }}
        uses: ncipollo/release-action@v1
        with:
          commit: '${{ github.sha }}'
          tag: '${{ steps.tag.outputs.tag }}'
          artifacts: "emacs-tree-sitter-module-${{ steps.tag.outputs.tag }}.zip,sha256sum.txt"
          artifactContentType: application/octet-stream
          name: tree-sitter module DLLs ${{ steps.tag.outputs.tag }}
          body: |
            tree-sitter module DLLs.

            ```
            ${{ steps.build.outputs.summary }}
            ```
