name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: |
           pacman -S --noconfirm --needed --noprogressbar make mingw-w64-x86_64-gcc
        shell: 'C:/shells/msys2bash.cmd {0}'

      - name: Build tree-sitter modules
        run: |
          export PATH=/mingw64/bin:$PATH

          sh build.sh bash

          ls -l dist
        shell: 'C:/shells/msys2bash.cmd {0}'

      - name: Archive
        id: archive
        run: |
          $VERSION = "${{ github.ref }}" -Replace "refs/tags/", ""
          $ARCHIVE = "emacs-tree-sitter-module-$VERSION.zip"

          cd dist
          Compress-Archive -Path *.dll -DestinationPath "../$ARCHIVE"
          cd ..
          $ARTIFACT_HASH = (Get-FileHash -Algorithm SHA256 "$ARCHIVE").Hash
          "$ARTIFACT_HASH  $ARCHIVE"| Out-File -Encoding ascii -File sha256sum.txt

          "hash=$ARTIFACT_HASH`n" | Out-File -NoNewline -Encoding utf8 -Append $env:GITHUB_OUTPUT
          "version=$VERSION`n" | Out-File -NoNewline -Encoding utf8 -Append $env:GITHUB_OUTPUT
          gc $env:GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "emacs-tree-sitter-module-${{ steps.archive.outputs.version }}.zip,sha256sum.txt"
          artifactContentType: application/octet-stream
          name: tree-sitter module DLLs ${{ steps.archive.outputs.version }}
          body: |
            tree-sitter module DLLs.

            | File | SHA-256 sum |
            | ---  | ---         |
            | emacs-tree-sitter-module-${{ steps.archive.outputs.version }}.zip | `${{ steps.archive.outputs.hash }}` |
